"""
Django settings for dracarys project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from xml.etree.ElementInclude import include
from django.conf.urls.i18n import i18n_patterns
import dj_database_url

from dotenv import load_dotenv
load_dotenv()  # Carga las variables de entorno desde el archivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
    
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "dracarys.onrender.com",
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://dracarys.onrender.com",
]

#USE_X_FORWARDED_HOST = True
#USE_X_FORWARDED_PORT = True

# Esto le dice a Django que confíe en el encabezado que envía ngrok
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    
]

JAZZMIN_SETTINGS = {
    # Títulos y Marcas
    "site_title": "Admin Dracarys",
    "site_header": "Dracarys",
    "site_brand": "Dracarys System",
    "site_logo": "img/logo.png",  # Asegúrate de tener esto en static/img/
    "login_logo": "img/logo.png", # Logo en la pantalla de login
    "welcome_sign": "Bienvenido al Sistema de Gestión Académica",
    "copyright": "Dracarys",

    # Búsqueda Global (Ctrl + /)
    # Permite buscar usuarios desde cualquier pantalla
    "search_model": "auth.User",

    # Menú de Usuario (Arriba a la derecha)
    # Lo dejamos automático para evitar el error de "no cerrar sesión"
    "usermenu_links": [
        {"model": "auth.user"}
    ],

    # Menú Lateral (Sidebar)
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # ICONOS (FontAwesome 5 Free)
    # Aquí es donde le damos personalidad a tus tablas
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # TUS MODELOS DE LA APP 'api'
        "api.Facultades": "fas fa-university",      # Un edificio universitario
        "api.Usuarios": "fas fa-user-graduate",     # Un estudiante graduado
        "api.Materias": "fas fa-book-open",         # Un libro abierto
        "api.InscripcionDeseada": "fas fa-clipboard-list", # Una lista de tareas/inscripción
        "api.UsuarioFacultad": "fas fa-id-card-alt", # Una credencial
    },

    # Orden del Menú Lateral
    # Puedes forzar el orden de las apps.
    #"order_with_respect_to": ["auth", "api", "api.Usuarios", "api.InscripcionDeseada"],

    # UI Builder
    # Ponlo en False cuando termines de configurar para que no moleste
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "superhero",
    "dark_mode_theme": "none",
    "navbar": "main-header navbar darkly navbar-expand navbar-dark",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dracarys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dracarys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Si no encuentra la variable 'DATABASE_URL', usa la local (Cochabamba)
        default=os.environ.get('DATABASE_URL', 'postgres://admin:dracarys123@localhost:5432/dracarys'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DRACARYS_API_KEY = os.environ.get('DRACARYS_API_KEY')
